# Generated by Django 5.0.7 on 2025-02-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_report_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pestle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
