# Generated by Django 5.0.7 on 2025-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_report_pestle_alter_report_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
